blank_issues_enabled: false
contact_links:
  - name: General issue
    url: https://github.com/gaurav-ketkar/resumescan/issues/new
    about: A new issue
  - name: Bug report
    url: https://github.com/gaurav-ketkar/resumescan/issues/new?assignee=gaurav-ketkar
    about: A bug report 
